name: Schedule Test

on:
  workflow_dispatch:
  schedule:
    - cron: "29 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Print current date
        run: |
          echo "Scheduled workflow is running!"
          date
